package apresentacao;

import database.ConectaBanco;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import persistencia.ModeloTabela;
/**
 * Created by Adriel on 10/05/2017.
 */
public class PesquisaPaciente extends javax.swing.JFrame {
    ConectaBanco con = new ConectaBanco();
    /**
     * Creates new form PesquisaPaciente
     */
    public PesquisaPaciente() {
        initComponents();
        con.Conexão();
        PreencheTabela("select * from paciente order by id");
    }
    public void PreencheTabela(String sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"id", "nome","telefone", "sexo"};
        con.Conexão();
        con.ExecutaSql(sql);

        try{
            con.rs.first();
            do{
                dados.add(new Object[]{
                        con.rs.getInt("id"), con.rs.getString("nome"),  con.rs.getString("telefone"), con.rs.getString("sexo"), con.rs.getString("cpf"), con.rs.getString("dataNascimento"), con.rs.getString("tipoConsulta")});
            }while(con.rs.next());
        }catch(Exception exc){
            JOptionPane.showMessageDialog(this, "Erro ao preencher o Array!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        ModeloTabela tab = new ModeloTabela(dados, colunas);
        tabPaciente.setModel(tab);
        tabPaciente.getColumnModel().getColumn(0).setPreferredWidth(23);
        tabPaciente.getColumnModel().getColumn(0).setResizable(false);
        tabPaciente.getColumnModel().getColumn(1).setPreferredWidth(180);
        tabPaciente.getColumnModel().getColumn(1).setResizable(false);
        tabPaciente.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabPaciente.getColumnModel().getColumn(2).setResizable(false);
        tabPaciente.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabPaciente.getColumnModel().getColumn(3).setResizable(false);
        tabPaciente.getTableHeader().setReorderingAllowed(false);
        tabPaciente.setAutoResizeMode(tabPaciente.AUTO_RESIZE_OFF);
        tabPaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        con.Desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPaciente = new javax.swing.JTable();
        jbNovo = new javax.swing.JToggleButton();
        jbEditar = new javax.swing.JToggleButton();
        jbDeletar = new javax.swing.JToggleButton();
        jbPesquisarPaciente = new javax.swing.JToggleButton();
        tfPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabPaciente.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {},
                        {},
                        {},
                        {}
                },
                new String [] {

                }
        ));
        jScrollPane1.setViewportView(tabPaciente);

        jbNovo.setText("Novo Paciente");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar Paciente");

        jbDeletar.setText("Excluir Paciente");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbPesquisarPaciente.setText("Pesquisar Paciente");
        jbPesquisarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jbPesquisarPaciente)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jbDeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jbEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jbNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbPesquisarPaciente)
                                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jbNovo)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbEditar)
                                                .addGap(16, 16, 16)
                                                .addComponent(jbDeletar))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(784, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {
        FormInclusaoPaciente janelaInclusao = new FormInclusaoPaciente(this, true);
        janelaInclusao.setVisible(true);
    }

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {
        con.ExecutaSql("delete from paciente where nome = " + tfPesquisa.getText());
    }

    private void jbPesquisarPacienteActionPerformed(java.awt.event.ActionEvent evt) {
        PreencheTabela("SELECT * FROM paciente WHERE nome LIKE'%" + tfPesquisa.getText()+"%'" );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbDeletar;
    private javax.swing.JToggleButton jbEditar;
    private javax.swing.JToggleButton jbNovo;
    private javax.swing.JToggleButton jbPesquisarPaciente;
    private javax.swing.JTable tabPaciente;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration

}
